pool:
  vmImage: 'ubuntu-latest'
variables:
  NodeVersion: 12
steps:
- checkout: self
  persistCredentials: true
- template: templates/build.yaml
- script: 'node common\scripts\install-run-rush.js version --bump --version-policy BOGUS --target-branch $(Build.SourceBranchName)'
  displayName: 'Rush Version'
- script: 'node common\scripts\install-run-rush.js publish --apply --publish --include-all --npm-auth-token $(npmToken)'
  displayName: 'Rush Publish'
