resources:
  - repo: self
variables:
  NodeVersion: 14
  FORCE_COLOR: 1
steps:
  - checkout: self
  - template: templates/build.yaml
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Playground Artifacts'
    inputs:
      PathtoPublish: playground/dist
      ArtifactName: playground
