pool:
  vmImage: 'ubuntu-latest'
resources:
  repositories:
    - repository: pagesBranch
      endpoint: 'GitHub (Rushbot)'
      type: github
      name: microsoft/tsdoc
      ref: refs/heads/gh-pages
      trigger: none
variables:
  NodeVersion: 14
  FORCE_COLOR: 1
jobs:
  - job: build
    displayName: Build
    steps:
      - checkout: self

      - template: ./templates/build.yaml

      - publish: playground/dist
        artifact: 'playground'
        displayName: 'Publish Playground Artifacts'

  - job: publish
    displayName: Publish
    dependsOn: build
    steps:
      - checkout: pagesBranch
        persistCredentials: true
      - script: git checkout gh-pages
        displayName: 'Checkout gh-pages Branch'

      - script: rm -r $(Build.SourcesDirectory)/*
        displayName: 'Clean Pages Branch'

      - task: DownloadPipelineArtifact@2
        displayName: 'Download Playground Artifacts'
        inputs:
          artifact: playground
          targetPath: $(Build.SourcesDirectory)

      - template: ./templates/configure-git.yaml

      - script: |
          git add -A
          if [ -n "$(git diff --name-only --staged HEAD --)" ]
          then
            echo "Committing changes"
            git commit -m "Update playground artifacts"
            git push
          else
            echo "No changes"
          fi
        displayName: 'Commit and push playground artifacts'
