steps:
  - task: NodeTool@0
    displayName: 'Use Node $(NodeVersion).x'
    inputs:
      versionSpec: '$(NodeVersion).x'
      checkLatest: true
  - template: ./configure-git.yaml
  - script: 'node common/scripts/install-run-rush.js change --verify'
    displayName: 'Verify Change Logs'
  - script: 'node common/scripts/install-run-rush.js check'
    displayName: 'Rush Check'
  - script: 'node common/scripts/install-run-rush.js install'
    displayName: 'Rush Install'
  - script: 'node common/scripts/install-run-rush.js retest --verbose --production'
    displayName: 'Rush retest'
    env:
      # Prevent time-based browserslist update warning
      # See https://github.com/microsoft/rushstack/issues/2981
      BROWSERSLIST_IGNORE_OLD_DATA: 1
