steps:
  - script: 'git config --local user.email rushbot@users.noreply.github.com'
    displayName: 'git config email'
    workingDirectory: '$(Agent.BuildDirectory)/tsdoc'

  - script: 'git config --local user.name Rushbot'
    displayName: 'git config name'
    workingDirectory: '$(Agent.BuildDirectory)/tsdoc'

  - script: 'node common/scripts/install-run-rush.js change --verify'
    displayName: 'Verify Change Logs'
    workingDirectory: '$(Agent.BuildDirectory)/tsdoc'

  - script: 'node common/scripts/install-run-rush.js install'
    displayName: 'Rush Install'
    workingDirectory: '$(Agent.BuildDirectory)/tsdoc'

  - script: 'node common/scripts/install-run-rush.js retest --verbose --production'
    displayName: 'Rush retest'
    workingDirectory: '$(Agent.BuildDirectory)/tsdoc'
