steps:
  - script: 'git config --local user.email rushbot@users.noreply.github.com'
    displayName: 'git config email'
  - script: 'git config --local user.name Rushbot'
    displayName: 'git config name'
