steps:
  - script: 'node common/scripts/install-run-rush.js version --bump --version-policy tsdoc --target-branch $(Build.SourceBranchName)'
    displayName: 'Rush Version'
    workingDirectory: '$(Agent.BuildDirectory)/tsdoc'

  - script: 'node common/scripts/install-run-rush.js publish --apply --publish --include-all --target-branch $(Build.SourceBranchName) --add-commit-details --set-access-level public'
    displayName: 'Rush Publish'
    env:
      NPM_AUTH_TOKEN: $(npmToken)
    workingDirectory: '$(Agent.BuildDirectory)/tsdoc'
